spring:
  datasource:


    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: AuthHikariCP
      max-lifetime: 60000
      connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true